# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookstore.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from extended_combo import *
import Resources_rc
import datetime


class Ui_BookStore(object):
    def setupUi(self, BookStore):
        
        BookStore.setObjectName("BookStore")
        BookStore.resize(1188, 763)
        BookStore.setMinimumSize(QtCore.QSize(1188, 763))
        BookStore.setMaximumSize(QtCore.QSize(1188, 763))
        BookStore.setStyleSheet("QWidget#centralwidget{\n"
"border-image: url(:/resources/background.jpg);\n"
"background-repeat: no-repeat;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BookStore.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BookStore)
        self.centralwidget.setMinimumSize(QtCore.QSize(1188, 763))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 90, 1171, 661))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("QTabWidget#tabWidget::pane {\n"
"border-top: 2px solid rgba(194, 199, 203, 0);\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.OPtab = QtWidgets.QWidget()
        self.OPtab.setStyleSheet("")
        self.OPtab.setObjectName("OPtab")
        self.widget = QtWidgets.QWidget(self.OPtab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1171, 631))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: rgba(255, 243, 235, 116);\n"
"}")
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 160, 1151, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnWidth ( 8, 500 ) 
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader()
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.setColumnWidth ( 8, 200 ) 
        self.BooknameLEdit =ExtendedComboBox(self.widget)
        self.BooknameLEdit.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.BooknameLEdit.setGeometry(QtCore.QRect(10, 40, 301, 41))
        self.BooknameLEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        
        self.BooknameLEdit.setObjectName("BooknameLEdit")
        self.addOPbtn_2 = QtWidgets.QPushButton(self.widget)
        self.addOPbtn_2.setGeometry(QtCore.QRect(700, 40, 141, 41))
        self.addOPbtn_2.setStyleSheet("")
        self.addOPbtn_2.setObjectName("addOPbtn_2")
        self.addClientbtn = QtWidgets.QPushButton(self.widget)
        self.addClientbtn.setGeometry(QtCore.QRect(1020, 40, 141, 41))
        self.addClientbtn.setStyleSheet("")
        self.addClientbtn.setObjectName("addClientbtn")
        self.refreshClients = QtWidgets.QPushButton(self.widget)
        self.refreshClients.setGeometry(QtCore.QRect(1020, 100, 141, 41))
        self.refreshClients.setStyleSheet("")
        self.refreshClients.setObjectName("refreshClients")
        self.addOPbtn = QtWidgets.QPushButton(self.widget)
        self.addOPbtn.setGeometry(QtCore.QRect(860, 40, 141, 41))
        self.addOPbtn.setStyleSheet("")
        self.addOPbtn.setObjectName("addOPbtn")
        self.comboBox_2 = ExtendedComboBox(self.widget)
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_2.setGeometry(QtCore.QRect(450, 40, 231, 41))
        self.comboBox_2.addItem('Unknown')
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(350, 40, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(350, 100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_2.setGeometry(QtCore.QRect(450, 100, 231, 41))
        self.spinBox_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_2.setMinimum(1)
        self.tabWidget.addTab(self.OPtab, "")
        self.StockTab = QtWidgets.QWidget()
        self.StockTab.setObjectName("StockTab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.StockTab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1151, 611))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("\n"
"\n"
"QTabWidget#tabWidget_2::pane{\n"
"border: 2px solid #ffffff;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgba(255, 243, 235, 116);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"left: 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:!selected {\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.ViewBookTab = QtWidgets.QWidget()
        self.ViewBookTab.setObjectName("ViewBookTab")
        self.BookNameField = QtWidgets.QLineEdit(self.ViewBookTab)
        self.BookNameField.setGeometry(QtCore.QRect(40, 30, 321, 41))
        self.BookNameField.setObjectName("BookNameField")
        self.BookstableWidget = QtWidgets.QTableWidget(self.ViewBookTab)
        self.BookstableWidget.setGeometry(QtCore.QRect(10, 140, 1131, 431))
        self.BookstableWidget.setAutoFillBackground(False)
        self.BookstableWidget.setObjectName("BookstableWidget")
        self.BookstableWidget.setColumnCount(7)
        self.BookstableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.BookstableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookstableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookstableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookstableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookstableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookstableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookstableWidget.setHorizontalHeaderItem(6, item)
        self.BookstableWidget.horizontalHeader().setDefaultSectionSize(188)
        self.pushButton_2 = QtWidgets.QPushButton(self.ViewBookTab)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 30, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget_2.addTab(self.ViewBookTab, "")
        self.AddBookTab = QtWidgets.QWidget()
        self.AddBookTab.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.AddBookTab.setObjectName("AddBookTab")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.AddBookTab)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 40, 421, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.AddBookTab)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 171, 31))
        self.label_3.setStyleSheet("")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.AddBookTab)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 150, 241, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.AddBookTab)
        self.label_5.setGeometry(QtCore.QRect(60, 300, 171, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.AddBookTab)
        self.label_6.setGeometry(QtCore.QRect(60, 200, 171, 31))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.AddBookTab)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 171, 31))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.AddBookTab)
        self.label_7.setGeometry(QtCore.QRect(60, 250, 171, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.AddBookTab)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 300, 241, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.AddBookTab)
        self.pushButton_10.setGeometry(QtCore.QRect(430, 430, 271, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.comboBox_3 = ExtendedComboBox(self.AddBookTab)
        self.comboBox_3.setGeometry(QtCore.QRect(240, 100, 241, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.AddBookTab)
        self.textEdit.setGeometry(QtCore.QRect(670, 40, 401, 311))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.AddBookTab)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 200, 241, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.AddBookTab)
        self.lineEdit_31.setGeometry(QtCore.QRect(240, 250, 241, 31))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.tabWidget_2.addTab(self.AddBookTab, "")
        self.EditBookTab = QtWidgets.QWidget()
        self.EditBookTab.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.EditBookTab.setObjectName("EditBookTab")
        self.pushButton_11 = QtWidgets.QPushButton(self.EditBookTab)
        self.pushButton_11.setGeometry(QtCore.QRect(850, 470, 181, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.EditBookTab)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 60, 241, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_13 = QtWidgets.QPushButton(self.EditBookTab)
        self.pushButton_13.setGeometry(QtCore.QRect(540, 470, 151, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_16 = QtWidgets.QLabel(self.EditBookTab)
        self.label_16.setGeometry(QtCore.QRect(520, 270, 171, 31))
        self.label_16.setObjectName("label_16")
        self.pushButton_12 = QtWidgets.QPushButton(self.EditBookTab)
        self.pushButton_12.setGeometry(QtCore.QRect(760, 60, 221, 35))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_12 = QtWidgets.QLabel(self.EditBookTab)
        self.label_12.setGeometry(QtCore.QRect(520, 120, 171, 31))
        self.label_12.setObjectName("label_12")
        self.textEdit_2 = QtWidgets.QTextEdit(self.EditBookTab)
        self.textEdit_2.setGeometry(QtCore.QRect(90, 200, 321, 301))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_13 = QtWidgets.QLabel(self.EditBookTab)
        self.label_13.setGeometry(QtCore.QRect(90, 60, 70, 31))
        self.label_13.setObjectName("label_13")
        self.comboBox_8 = ExtendedComboBox(self.EditBookTab)
        self.comboBox_8.setGeometry(QtCore.QRect(752, 120, 241, 31))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.label_10 = QtWidgets.QLabel(self.EditBookTab)
        self.label_10.setGeometry(QtCore.QRect(520, 170, 171, 31))
        self.label_10.setObjectName("label_10")
        self.comboBox_10 = QtWidgets.QComboBox(self.EditBookTab)
        self.comboBox_10.setGeometry(QtCore.QRect(750, 270, 241, 31))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.label_15 = QtWidgets.QLabel(self.EditBookTab)
        self.label_15.setGeometry(QtCore.QRect(520, 220, 171, 31))
        self.label_15.setObjectName("label_15")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.EditBookTab)
        self.lineEdit_12.setGeometry(QtCore.QRect(750, 220, 241, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.EditBookTab)
        self.lineEdit_13.setGeometry(QtCore.QRect(750, 270, 241, 31))
        self.lineEdit_13.setObjectName("lineEdit_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.EditBookTab)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 120, 321, 61))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.EditBookTab)
        self.lineEdit_10.setGeometry(QtCore.QRect(750, 170, 241, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.tabWidget_2.addTab(self.EditBookTab, "")
        self.tabWidget.addTab(self.StockTab, "")
        self.ClientsTab = QtWidgets.QWidget()
        self.ClientsTab.setObjectName("ClientsTab")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.ClientsTab)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 1161, 631))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setStyleSheet("QTabWidget#tabWidget_3::pane{\n"
"border: 2px solid #ffffff;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgba(255, 243, 235, 116);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"left: 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:!selected {\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.tabWidget_3.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget_3.setGeometry(QtCore.QRect(461, 30, 681, 521))
        self.tableWidget_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_3.setLineWidth(1)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidget_3.horizontalHeader().setHighlightSections(True)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_14.setGeometry(QtCore.QRect(270, 70, 181, 41))
        self.pushButton_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 70, 231, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_16.setGeometry(QtCore.QRect(580, 270, 241, 31))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_16.setGeometry(QtCore.QRect(640, 390, 231, 61))
        self.pushButton_16.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_16.setObjectName("pushButton_16")
        
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_19.setGeometry(QtCore.QRect(580, 190, 241, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_18.setGeometry(QtCore.QRect(270, 390, 231, 61))
        self.pushButton_18.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_18.setObjectName("pushButton_18")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_13)
        self.comboBox_11.setGeometry(QtCore.QRect(500, 90, 201, 31))
        self.comboBox_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")

        self.label_20 = QtWidgets.QLabel(self.tab_13)
        self.label_20.setGeometry(QtCore.QRect(340, 270, 221, 31))
        self.label_20.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_17.setGeometry(QtCore.QRect(770, 90, 191, 31))
        self.pushButton_17.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_20.setGeometry(QtCore.QRect(140, 90, 291, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_23 = QtWidgets.QLabel(self.tab_13)
        self.label_23.setGeometry(QtCore.QRect(340, 190, 221, 31))
        self.label_23.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_21.setGeometry(QtCore.QRect(580, 290, 241, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab)
        self.pushButton_19.setGeometry(QtCore.QRect(640, 390, 231, 61))
        self.pushButton_19.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_19.setObjectName("pushButton_19")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_22.setGeometry(QtCore.QRect(580, 240, 241, 31))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_23.setGeometry(QtCore.QRect(580, 190, 241, 31))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(340, 240, 221, 31))
        self.label_27.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab)
        self.pushButton_25.setGeometry(QtCore.QRect(270, 390, 231, 61))
        self.pushButton_25.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_25.setObjectName("pushButton_25")
        self.comboBox_14 = QtWidgets.QComboBox(self.tab)
        self.comboBox_14.setGeometry(QtCore.QRect(500, 90, 201, 31))
        self.comboBox_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(340, 290, 221, 31))
        self.label_32.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_32.setObjectName("label_32")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab)
        self.pushButton_26.setGeometry(QtCore.QRect(770, 90, 191, 31))
        self.pushButton_26.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_26.setObjectName("pushButton_26")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_25.setGeometry(QtCore.QRect(140, 90, 291, 31))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(340, 190, 221, 31))
        self.label_33.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.tabWidget_3.addTab(self.tab, "")
        self.tabWidget.addTab(self.ClientsTab, "")
        self.ReportTab = QtWidgets.QWidget()
        self.ReportTab.setObjectName("ReportTab")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.ReportTab)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 1171, 631))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_5.setFont(font)
        self.tabWidget_5.setStyleSheet("QTabWidget#tabWidget_5::pane{\n"
"border: 2px solid #ffffff;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgba(255, 243, 235, 116);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"left: 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:!selected {\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.tabWidget_5.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_18)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 90, 1151, 451))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        self.dateEdit = QtWidgets.QDateEdit(self.tab_18)
        self.dateEdit.setGeometry(QtCore.QRect(80, 20, 121, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.label_28 = QtWidgets.QLabel(self.tab_18)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_18)
        self.label_29.setGeometry(QtCore.QRect(260, 20, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_18)
        self.dateEdit_2.setGeometry(QtCore.QRect(290, 20, 121, 31))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_2.setDate(datetime.date.today())
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_24.setGeometry(QtCore.QRect(520, 20, 161, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_41 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_41.setGeometry(QtCore.QRect(970, 550, 181, 41))
        self.pushButton_41.setObjectName("pushButton_41")
        self.tabWidget_5.addTab(self.tab_18, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 20, 521, 531))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(4)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(640, 70, 431, 51))
        self.lineEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(770, 165, 301, 41))
        self.comboBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(640, 160, 111, 51))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(770, 245, 301, 41))
        self.spinBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(640, 240, 141, 51))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(740, 320, 211, 51))
        self.pushButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(610, 460, 501, 91))
        self.groupBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 301, 51))
        self.lineEdit_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 30, 161, 51))
        self.pushButton_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.tabWidget_5.addTab(self.tab_2, "")
        self.tabWidget.addTab(self.ReportTab, "")
        self.SettingsTab = QtWidgets.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.SettingsTab)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1171, 631))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setStyleSheet("QTabWidget#tabWidget_4::pane{\n"
"border: 2px solid #ffffff;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgba(255, 243, 235, 116);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"left: 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:!selected {\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.tabWidget_4.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.tab_14.setObjectName("tab_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_14)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 160, 1021, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 50, 241, 31))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(510, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_20.setGeometry(QtCore.QRect(810, 30, 201, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_51.setGeometry(QtCore.QRect(510, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_51.setFont(font)
        self.lineEdit_51.setObjectName("lineEdit_51")
        
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_14)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 290, 1021, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_28.setGeometry(QtCore.QRect(10, 40, 241, 31))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setGeometry(QtCore.QRect(810, 40, 201, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_27.setGeometry(QtCore.QRect(580, 40, 201, 31))
        self.pushButton_27.setObjectName("pushButton_27")
        
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_14)
        self.groupBox_7.setGeometry(QtCore.QRect(70, 40, 1021, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_32.setGeometry(QtCore.QRect(10, 50, 241, 31))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_23.setGeometry(QtCore.QRect(810, 30, 201, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_33.setGeometry(QtCore.QRect(510, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_48.setGeometry(QtCore.QRect(510, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_48.setFont(font)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.tab_15.setObjectName("tab_15")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_5.setGeometry(QtCore.QRect(50, 40, 481, 481))
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_34.setGeometry(QtCore.QRect(230, 30, 241, 31))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_44 = QtWidgets.QLabel(self.groupBox_5)
        self.label_44.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setGeometry(QtCore.QRect(10, 130, 221, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(10, 180, 221, 31))
        self.label_46.setObjectName("label_46")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_35.setGeometry(QtCore.QRect(230, 80, 241, 31))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_36.setGeometry(QtCore.QRect(230, 130, 241, 31))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_47 = QtWidgets.QLabel(self.groupBox_5)
        self.label_47.setGeometry(QtCore.QRect(10, 80, 221, 31))
        self.label_47.setObjectName("label_47")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_37.setGeometry(QtCore.QRect(230, 180, 241, 31))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_38.setGeometry(QtCore.QRect(230, 230, 241, 31))
        self.lineEdit_38.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.label_48 = QtWidgets.QLabel(self.groupBox_5)
        self.label_48.setGeometry(QtCore.QRect(10, 230, 221, 31))
        self.label_48.setObjectName("label_48")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_39.setGeometry(QtCore.QRect(230, 280, 241, 31))
        self.lineEdit_39.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.label_49 = QtWidgets.QLabel(self.groupBox_5)
        self.label_49.setGeometry(QtCore.QRect(10, 280, 221, 31))
        self.label_49.setObjectName("label_49")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_30.setGeometry(QtCore.QRect(150, 430, 201, 41))
        self.pushButton_30.setObjectName("pushButton_30")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setGeometry(QtCore.QRect(230, 340, 201, 41))
        self.checkBox.setObjectName("checkBox")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_6.setGeometry(QtCore.QRect(590, 40, 511, 481))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_40.setGeometry(QtCore.QRect(240, 40, 241, 31))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_50 = QtWidgets.QLabel(self.groupBox_6)
        self.label_50.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_6)
        self.label_51.setGeometry(QtCore.QRect(10, 230, 221, 31))
        self.label_51.setObjectName("label_51")
        self.label_53 = QtWidgets.QLabel(self.groupBox_6)
        self.label_53.setGeometry(QtCore.QRect(10, 270, 221, 31))
        self.label_53.setObjectName("label_53")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_41.setGeometry(QtCore.QRect(240, 190, 241, 31))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_42.setGeometry(QtCore.QRect(240, 230, 241, 31))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.label_54 = QtWidgets.QLabel(self.groupBox_6)
        self.label_54.setGeometry(QtCore.QRect(10, 190, 221, 31))
        self.label_54.setObjectName("label_54")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_43.setGeometry(QtCore.QRect(240, 270, 241, 31))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_44.setGeometry(QtCore.QRect(240, 310, 241, 31))
        self.lineEdit_44.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.label_55 = QtWidgets.QLabel(self.groupBox_6)
        self.label_55.setGeometry(QtCore.QRect(10, 310, 221, 31))
        self.label_55.setObjectName("label_55")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 350, 411, 31))
        self.label_11.setObjectName("label_11")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_31.setGeometry(QtCore.QRect(20, 430, 201, 41))
        self.pushButton_31.setObjectName("pushButton_31")
        self.label_56 = QtWidgets.QLabel(self.groupBox_6)
        self.label_56.setGeometry(QtCore.QRect(10, 80, 221, 31))
        self.label_56.setObjectName("label_56")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_46.setGeometry(QtCore.QRect(240, 80, 241, 31))
        self.lineEdit_46.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_32.setGeometry(QtCore.QRect(150, 140, 201, 41))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_33.setGeometry(QtCore.QRect(260, 430, 201, 41))
        self.pushButton_33.setObjectName("pushButton_33")
        self.tabWidget_4.addTab(self.tab_15, "")
        self.tabWidget.addTab(self.SettingsTab, "")
        self.NavBar = QtWidgets.QGroupBox(self.centralwidget)
        self.NavBar.setGeometry(QtCore.QRect(20, 10, 1151, 71))
        self.NavBar.setStyleSheet("QPushButton{\n"
"padding:10px\n"
"\n"
"}\n"
"QGroupBox#NavBar{\n"
"border: 2px solid #ffffff;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"background-color: rgba(193, 193, 193, 150);\n"
"}")
        self.NavBar.setObjectName("NavBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.NavBar)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OperationsBtn = QtWidgets.QPushButton(self.NavBar)
        self.OperationsBtn.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/daily.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OperationsBtn.setIcon(icon)
        self.OperationsBtn.setFlat(False)
        self.OperationsBtn.setObjectName("OperationsBtn")
        self.horizontalLayout_2.addWidget(self.OperationsBtn)
        self.StockBtn = QtWidgets.QPushButton(self.NavBar)
        self.StockBtn.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StockBtn.setIcon(icon1)
        self.StockBtn.setObjectName("StockBtn")
        self.horizontalLayout_2.addWidget(self.StockBtn)
        self.ClientsBtn = QtWidgets.QPushButton(self.NavBar)
        self.ClientsBtn.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClientsBtn.setIcon(icon2)
        self.ClientsBtn.setObjectName("ClientsBtn")
        self.horizontalLayout_2.addWidget(self.ClientsBtn)
        self.ReportBtn = QtWidgets.QPushButton(self.NavBar)
        self.ReportBtn.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ReportBtn.setIcon(icon3)
        self.ReportBtn.setObjectName("ReportBtn")
        self.horizontalLayout_2.addWidget(self.ReportBtn)
        self.SettingsBtn = QtWidgets.QPushButton(self.NavBar)
        self.SettingsBtn.setEnabled(True)
        self.SettingsBtn.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsBtn.setIcon(icon4)
        self.SettingsBtn.setObjectName("SettingsBtn")
        self.horizontalLayout_2.addWidget(self.SettingsBtn)

        self.Logoutbtn = QtWidgets.QPushButton(self.NavBar)
        self.Logoutbtn.setEnabled(True)
        self.Logoutbtn.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        
        
        self.Logoutbtn.setObjectName("Logoutbtn")
        self.horizontalLayout_2.addWidget(self.Logoutbtn)

        self.NavBar.raise_()
        self.tabWidget.raise_()
        BookStore.setCentralWidget(self.centralwidget)

        self.retranslateUi(BookStore)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BookStore)

    def retranslateUi(self, BookStore):
        _translate = QtCore.QCoreApplication.translate
        BookStore.setWindowTitle(_translate("BookStore", "EAR BookStore Management"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BookStore", "Book id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BookStore", "Book name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("BookStore", "Category"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("BookStore", "Operation"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("BookStore", "Operation id"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("BookStore", "Client"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("BookStore", "Price"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("BookStore", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("BookStore", "Time"))
       
        self.addOPbtn_2.setText(_translate("BookStore", "Sale"))
        self.addClientbtn.setText(_translate("BookStore", "Add Client"))
        self.refreshClients.setText(_translate("BookStore", "Refresh clients"))
        self.addOPbtn.setText(_translate("BookStore", "Request"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OPtab), _translate("BookStore", "Operations"))
        self.BookNameField.setPlaceholderText(_translate("BookStore", "Book title"))
        
        item = self.BookstableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BookStore", "Book Id"))
        item = self.BookstableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BookStore", "Book name"))
        item = self.BookstableWidget.horizontalHeaderItem(2)
        item.setText(_translate("BookStore", "Category"))
        item = self.BookstableWidget.horizontalHeaderItem(3)
        item.setText(_translate("BookStore", "Author"))
        item = self.BookstableWidget.horizontalHeaderItem(4)
        item.setText(_translate("BookStore", "Publisher"))
        item = self.BookstableWidget.horizontalHeaderItem(5)
        item.setText(_translate("BookStore", "Price"))
        item = self.BookstableWidget.horizontalHeaderItem(6)
        item.setText(_translate("BookStore", "Copies in Stock"))
        self.pushButton_2.setText(_translate("BookStore", "Search"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.ViewBookTab), _translate("BookStore", "View Stock"))
        self.lineEdit_3.setPlaceholderText(_translate("BookStore", "book title"))
        self.label_3.setText(_translate("BookStore", "Category"))
        self.label_5.setText(_translate("BookStore", "Amount in stock"))
        self.label_6.setText(_translate("BookStore", "Publisher"))
        self.label_4.setText(_translate("BookStore", "Price"))
        self.label_7.setText(_translate("BookStore", "Author"))
        self.pushButton_10.setText(_translate("BookStore", "Add book"))
        self.textEdit.setPlaceholderText(_translate("BookStore", "Short Description (Optional)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.AddBookTab), _translate("BookStore", "Add New Book"))
        self.pushButton_11.setText(_translate("BookStore", "save book"))
        self.pushButton_13.setText(_translate("BookStore", "delete book"))
        self.label_16.setText(_translate("BookStore", "Author"))
        self.pushButton_12.setText(_translate("BookStore", "search"))
        self.label_12.setText(_translate("BookStore", "Category"))
        self.textEdit_2.setPlaceholderText(_translate("BookStore", "book description"))
        self.label_13.setText(_translate("BookStore", "Code"))
        self.comboBox_8.setItemText(0, _translate("BookStore", "------------"))
        self.label_10.setText(_translate("BookStore", "Price"))
        self.comboBox_10.setItemText(0, _translate("BookStore", "------------"))
        self.label_15.setText(_translate("BookStore", "Publisher"))
        
        self.lineEdit_9.setPlaceholderText(_translate("BookStore", "book title"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.EditBookTab), _translate("BookStore", "Edit Book Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StockTab), _translate("BookStore", "Stock"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("BookStore", "Client name "))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("BookStore", "Phone"))
        
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("BookStore", "Join date"))
        self.label_8.setText(_translate("BookStore", "Client name"))
        self.label_9.setText(_translate("BookStore", "Quantity"))
        
        self.pushButton_14.setText(_translate("BookStore", "Search"))
        self.lineEdit_11.setPlaceholderText(_translate("BookStore", "client name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("BookStore", "all clients"))
        self.pushButton_16.setText(_translate("BookStore", "save data"))
        
        self.pushButton_18.setText(_translate("BookStore", "delete data"))
        self.comboBox_11.setItemText(0, _translate("BookStore", "client name"))

        self.comboBox_11.setItemText(1, _translate("BookStore", "client phone"))
        self.label_20.setText(_translate("BookStore", "phone"))
        self.pushButton_17.setText(_translate("BookStore", "search"))
        self.lineEdit_20.setPlaceholderText(_translate("BookStore", "Enter client data"))
        self.label_23.setText(_translate("BookStore", "client name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("BookStore", "edit or delete"))
        self.pushButton_19.setText(_translate("BookStore", "save data"))
        self.label_27.setText(_translate("BookStore", "mail"))
        self.pushButton_25.setText(_translate("BookStore", "delete data"))
        self.comboBox_14.setItemText(0, _translate("BookStore", "supplier name"))
        self.comboBox_14.setItemText(1, _translate("BookStore", "supplier mail"))
        self.comboBox_14.setItemText(2, _translate("BookStore", "supplier phone"))
        self.label_32.setText(_translate("BookStore", "phone"))
        self.pushButton_26.setText(_translate("BookStore", "search"))
        self.lineEdit_25.setPlaceholderText(_translate("BookStore", "Enter supplier data"))
        self.label_33.setText(_translate("BookStore", "supplier name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("BookStore", "Edit or delete supplier"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ClientsTab), _translate("BookStore", "Clients and suppliers"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("BookStore", "Code"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("BookStore", "Title"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("BookStore", "Category"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("BookStore", "Author"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("BookStore", "Price"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("BookStore", "Quantity"))
        self.label_28.setText(_translate("BookStore", "From"))
        self.label_29.setText(_translate("BookStore", "To"))
        self.pushButton_24.setText(_translate("BookStore", "Search"))
        self.pushButton_41.setText(_translate("BookStore", "Make report"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_18), _translate("BookStore", "Book reports"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("BookStore", "ID"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("BookStore", "Book name"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("BookStore", "Quantity"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("BookStore", "Date added"))
        self.lineEdit.setPlaceholderText(_translate("BookStore", "Request Id"))
        self.label.setText(_translate("BookStore", "Supplier"))
        self.label_2.setText(_translate("BookStore", "Quantity"))
        self.pushButton.setText(_translate("BookStore", "Send Request"))
        self.groupBox.setTitle(_translate("BookStore", "Remove Request"))
        self.lineEdit_2.setPlaceholderText(_translate("BookStore", "Request ID"))
        self.pushButton_3.setText(_translate("BookStore", "Remove"))
        
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_2), _translate("BookStore", "Check Requests"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ReportTab), _translate("BookStore", "Report"))
        self.groupBox_2.setTitle(_translate("BookStore", "Add publisher"))
        self.lineEdit_24.setPlaceholderText(_translate("BookStore", "publisher name"))
        self.lineEdit_26.setPlaceholderText(_translate("BookStore", "publisher Email"))
        self.pushButton_20.setText(_translate("BookStore", "Add"))
        self.lineEdit_51.setPlaceholderText(_translate("BookStore", "publisher Address"))

        self.groupBox_4.setTitle(_translate("BookStore", "Add category"))
        self.lineEdit_28.setPlaceholderText(_translate("BookStore", "category name"))
        self.pushButton_22.setText(_translate("BookStore", "Add"))
        self.pushButton_27.setText(_translate("BookStore", "delete"))

        self.groupBox_7.setTitle(_translate("BookStore", "Add Supplier"))
        self.lineEdit_32.setPlaceholderText(_translate("BookStore", "supplier name"))
        self.pushButton_23.setText(_translate("BookStore", "Add"))
        self.lineEdit_33.setPlaceholderText(_translate("BookStore", "Email"))
        self.lineEdit_48.setPlaceholderText(_translate("BookStore", "Phone"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("BookStore", "Add Data"))
        self.groupBox_5.setTitle(_translate("BookStore", "Add employee"))
        self.label_44.setText(_translate("BookStore", "Employee name"))
        self.label_45.setText(_translate("BookStore", "phone"))
        self.label_46.setText(_translate("BookStore", "national ID"))
        self.label_47.setText(_translate("BookStore", "mail"))
        self.label_48.setText(_translate("BookStore", "password"))
        self.label_49.setText(_translate("BookStore", "repeat password"))
        self.pushButton_30.setText(_translate("BookStore", "Add employee"))
        self.groupBox_6.setTitle(_translate("BookStore", "Edit employee information"))
        self.label_50.setText(_translate("BookStore", "Employee name"))
        self.label_51.setText(_translate("BookStore", "phone"))
        self.label_53.setText(_translate("BookStore", "national ID"))
        self.label_54.setText(_translate("BookStore", "mail"))
        self.label_55.setText(_translate("BookStore", "password"))
        self.label_11.setText(_translate("BookStore", "*leave password field empty to keep the old password"))
        self.pushButton_31.setText(_translate("BookStore", "Save"))
        self.label_56.setText(_translate("BookStore", "password"))
        self.pushButton_32.setText(_translate("BookStore", "Check"))
        self.pushButton_33.setText(_translate("BookStore", "Delete Employee"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), _translate("BookStore", "Add Employee"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SettingsTab), _translate("BookStore", "Settings"))
        self.OperationsBtn.setText(_translate("BookStore", "operations"))
        self.StockBtn.setText(_translate("BookStore", "Stock"))
        self.ClientsBtn.setText(_translate("BookStore", "Clients and Suppliers"))
        self.ReportBtn.setText(_translate("BookStore", "Report"))
        self.SettingsBtn.setText(_translate("BookStore", "settings"))
        self.Logoutbtn.setText(_translate("BookStore", "Log out"))
        self.checkBox.setText(_translate("BookStore", "Is admin"))

